import { Inter } from "next/font/google";
import "./globals.css";

import Application from "./components/Application";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RADHEY MUKUND SALES LLP",
  description: "Generated by gagan yadav",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

<Application>
{children}
</Application>
        
     
        
        </body>
    </html>
  );
}
